services:
  echo-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
    networks:
      mynetwork:
        ipv4_address: 172.23.0.10

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
